# Cálculo de determinantes de matrices con `numpy`

Vamos a calcular con la computadora el determinante de esta matriz:
$$
\begin{pmatrix}
        12 & 7 & 0 \\
        6 & 7 & 0 \\
        5 & 8 & 3
\end{pmatrix}
$$

In [1]:
import numpy as np

In [3]:
A=np.array([
    [12, 7, 0],
    [6, 7, 0],
    [5, 8, 3]]
)
print(A)

[[12  7  0]
 [ 6  7  0]
 [ 5  8  3]]


_Recuerden que los intervalos en `Python` son *cerrados por la izquierda y abiertos por la derecha*_

In [7]:
for i in range(5):
    print(i)

0
1
2
3
4


La entrada $a_{23}$ de $A$ se representará en la computadora como `A[1,2]`

In [8]:
A[1,2]

0

Para obtener el determinante de $A$ ($\det A=|A|$), recurrimos a la función `np.linalg.det()`

In [10]:
np.linalg.det(A)

126.0

Repetimos este procedimiento para los demás incisos:

In [11]:
np.linalg.det(
    [
        [8,3,2],
        [5,1,3],
        [6,4,7]
    ]
)

-62.99999999999999

In [12]:
np.linalg.det(
    [
        [2,5,8,3],
        [3,10,2,1],
        [2,4,7,1],
        [1,15,0,4]
    ]
)

282.00000000000006

## Adjunta de una matriz

No hay una función que directamente calcule la adjunta de una matriz. Sin embargo, se puede obtener de forma indirecta mediante la inversa y el determinante. Por ejemplo, para la matriz `A` definida en las primeras celdas, la adjunta se calcula así:
$$ \text{Adj}(A)=\det A \times A^{-1}$$

In [14]:
np.linalg.inv(A)*np.linalg.det(A)

array([[ 21., -21.,   0.],
       [-18.,  36.,   0.],
       [ 13., -61.,  42.]])

$$B:=\begin{pmatrix} 
1 & -1 & 1 \\
0 & 2 & -1 \\
1 & 0 & 0
\end{pmatrix}$$

In [15]:
B=np.array([
    [1,-1,1],
    [0,2,-1],
    [1,0,0]
])

Juntamos en una sola función el determinante y la inversa, para obtener la adjunta:

In [16]:
def adj(X):
    return np.linalg.inv(X)*np.linalg.det(X)

In [17]:
adj(B)

array([[-0., -0., -1.],
       [-1., -1.,  1.],
       [-2., -1.,  2.]])