# Cálculo de determinantes de matrices con `numpy`

Vamos a calcular con la computadora el determinante de esta matriz:
$$
\begin{pmatrix}
        12 & 7 & 0 \\
        6 & 7 & 0 \\
        5 & 8 & 3
\end{pmatrix}
$$

In [1]:
import numpy as np

In [3]:
A=np.array([
    [12, 7, 0],
    [6, 7, 0],
    [5, 8, 3]]
)
print(A)

[[12  7  0]
 [ 6  7  0]
 [ 5  8  3]]


_Recuerden que los intervalos en `Python` son *cerrados por la izquierda y abiertos por la derecha*_

In [7]:
for i in range(5):
    print(i)

0
1
2
3
4


La entrada $a_{23}$ de $A$ se representará en la computadora como `A[1,2]`

In [8]:
A[1,2]

0

Para obtener el determinante de $A$ ($\det A=|A|$), recurrimos a la función `np.linalg.det()`

In [10]:
np.linalg.det(A)

126.0

Repetimos este procedimiento para los demás incisos:

In [11]:
np.linalg.det(
    [
        [8,3,2],
        [5,1,3],
        [6,4,7]
    ]
)

-62.99999999999999

In [12]:
np.linalg.det(
    [
        [2,5,8,3],
        [3,10,2,1],
        [2,4,7,1],
        [1,15,0,4]
    ]
)

282.00000000000006